spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: Akhil@123

    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "health,beans,metrics"
      base-path: "/management-dashboard"
  endpoint:
    health:
      show-details: always